### ISSUE TITLE
Diagrama De Secuencia

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-tecno-power#1]
[Diagrama De Secuencia_tecno-power.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-tecno-power/files/7819151/Diagrama.De.Secuencia_tecno-power.pdf)

**Comment by salathiel1999** [comment]
Calificación-28 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado
